name: CI

on: [push]

jobs:
  static_checks:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./extension
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - run: pnpm install --prefer-offline
      - name: Run static checks
        run: pnpm check
  unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./extension
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - run: pnpm install --prefer-offline
      - run: pnpm test:unit --coverage
      - name: 'Report Coverage'
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always() 
        uses:  davelosert/vitest-coverage-report-action@v2
