name: Live tests

on:
  deployment_status:

jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    defaults:
      run:
        working-directory: ${{ contains(github.event.deployment_status.target_url,'zodiac-pilot-example') && './deployables/extension' || './deployables/app' }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install --prefer-offline
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps chromium

      - name: Extension E2E
        run: xvfb-run pnpm playwright test
        if: ${{ contains(github.event.deployment_status.target_url,'zodiac-pilot-example')}}
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
          VERCEL_PROTECTION_BYPASS: ${{ secrets.VERCEL_PROTECTION_BYPASS }}
          PW_CHROMIUM_ATTACH_TO_OTHER: 1

      - name: Companion E2E
        run: xvfb-run pnpm playwright test
        if: ${{ contains(github.event.deployment_status.target_url,'zodiac-pilot-companion')}}
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
          VERCEL_PROTECTION_BYPASS: ${{ secrets.VERCEL_PROTECTION_BYPASS }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
