name: Live Tests

on:
  deployment_status:

jobs:
  playwright-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      CONNECT_IFRAME_URL: https://app.pilot.gnosisguild.org
    if: github.event.deployment_status.state == 'success'
    defaults:
      run:
        working-directory: ./deployables/extension
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install --prefer-offline

      - name: Build
        run: pnpm build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps chromium

      - name: Run Playwright tests
        run: xvfb-run pnpm playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
          VERCEL_PROTECTION_BYPASS: ${{ secrets.VERCEL_PROTECTION_BYPASS }}
          PW_CHROMIUM_ATTACH_TO_OTHER: 1

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
