name: Deploy Vnet API

on:
  push:
    branches: main
    paths: "vnet-api/**"

defaults:
  run:
    working-directory: ./vnet-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "pnpm"
          cache-dependency-path: "vnet-api/pnpm-lock.yaml"
      - run: pnpm install
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          workingDirectory: vnet-api
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            TENDERLY_ACCESS_KEY
        env:
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
          TENDERLY_USER: gnosisguild
          TENDERLY_PROJECT: zodiac-pilot
